base/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from polls import views

app_name = 'polls'
urlpatterns = [
    path('student/<int:student_id>/', views.student_detail, name='student_detail'),
    path('<str:group_name>/', views.students, name='students'),
    path('students/add_student/', views.add_student, name='add_student'),
]

polls/models.py
from django.db import models


class Group(models.Model):
    group_name = models.CharField(max_length=100, verbose_name='Group name')

    def __str__(self):
        return '%s' % self.group_name


class Student(models.Model):
    name = models.CharField(max_length=50, verbose_name='Full name')
    date_of_birth = models.DateField(verbose_name='Date of birth')
    group = models.ForeignKey(Group, verbose_name='Group', on_delete=models.CASCADE)

    def __str__(self):
        return '%s' % self.name

polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect

from datetime import datetime

from polls.models import Student, Group


def students(request, group_name):
    students = Student.objects.filter(group__group_name=group_name)
    groups = Group.objects.all()
    context = {'students': students,
               'groups': groups
               }
    return render(request, 'polls/students.html', context)


def student_detail(request, student_id):
    student = Student.objects.get(pk=student_id)
    context = {'student': student}
    return render(request, 'polls/student_detail.html', context)


def add_student(request):
    student_name = request.POST.get('name')
    group_id = request.POST.get('group')
    birthday = datetime.today()
    new_sudent = Student(name=student_name, date_of_birth=birthday, group_id=group_id)
    new_sudent.save()
    return redirect(request.META['HTTP_REFERER'])

polls/templates/polls/student_detail.html
Name: {{ student.name }}<br/>
Birthday:  {{ student.date_of_birth}}

polls/templates/polls/students.html
{% load staticfiles %}
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>

{% if students %}
    <ul class="list-group">
        {% for student in students %}
            <li class="list-group-item">
                <a
                        href="{% url 'polls:student_detail' student.id %}">
                    {{ student.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<form action="{% url 'polls:add_student'%}" method="post">
    {% csrf_token %}
    <label for="studentName">Name:</label>
    <input type="text" name="name" title="name" class="form-control" id="studentName"
           placeholder="Full name">
    <label for="groupSelect">Group name:</label>
    <select name="group" class="form-control" id="groupSelect" title="group">
        {% for group in groups %}
            <option value="{{ group.id }}">{{ group.group_name }}</option>
        {% endfor %}
    </select>
    <input type="submit" class="btn btn-outline-success" value="Add" />
</form>